server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
spring:
  application:
    name: gateway-server
  profiles:
    active: path_route
---
spring:
  profiles: method_route
  cloud:
    gateway:
      routes:
      - id: method_route
        uri: http://localhost:9002/get
        predicates:
        - Method=GET
---
spring:
  cloud:
    gateway:
      routes:
      - id: path_route
        uri: http://localhost:9002/get
        predicates:
        - Path=/get
  profiles: path_route