server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
spring:
  application:
    name: gateway-server
  profiles:
    active: limit_route
---
spring:
  profiles: method_route
  cloud:
    gateway:
      routes:
      - id: method_route
        uri: http://localhost:9002/get
        predicates:
        - Method=GET
---
spring:
  cloud:
    gateway:
      routes:
      - id: path_route
        uri: http://localhost:9002/get
        predicates:
        - Path=/get
  profiles: path_route

---
spring:
  cloud:
    gateway:
      routes:
      - id: limit_route
        uri: http://localhost:9002/get
        predicates:
        - Path=/get
        filters:
          - name: RequestRateLimiter
            args:
              key-resolver: '#{@hostAddrKeyResolver}'
              redis-rate-limiter.replenishRate: 1
              redis-rate-limiter.burstCapacity: 1
  profiles: path_route

  # redis-cli.exe -h 127.0.0.1 -p 6379  启动redis  本地cmd
  redis:
    host: localhost
    database: 0
    port: 6379