server:
  port: 9004
spring:
  application:
    name: client-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sudo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: password
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  client:
    instance:
      hostname: client-user
    service-url:
      defaultZone: http://localhost:8000/eureka
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  type-aliases-package: sudo.client_user.mapper

logging:
  config: D:/soft/data/DS/sudo/client_user/src/main/resources/config/locbak.xml
  level:
    sudo.client_user: trace

