server:
  port: 6000
spring:
  profiles:
    active: route_simple
  application:
    name: route_simple
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: route_simple
          uri: http://localhost:8000
          predicates:
            - Path=/c
          filters:
            - name: RequestSize
              args:
                maxSize: 5000000
eureka:
  instance:
    hostname: gateway
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka

