# 应用名称
#spring.application.name=sentinel-server
# Sentinel 控制台地址
#spring.cloud.sentinel.transport.dashboard=localhost:8080
# 取消Sentinel控制台懒加载
# 默认情况下 Sentinel 会在客户端首次调用的时候进行初始化，开始向控制台发送心跳包
# 配置 sentinel.eager=true 时，取消Sentinel控制台懒加载功能
#spring.cloud.sentinel.eager=true
# 如果有多套网络，又无法正确获取本机IP，则需要使用下面的参数设置当前机器可被外部访问的IP地址，供admin控制台使用
# spring.cloud.sentinel.transport.client-ip=
#下载的Sentinel的包在D:/sentinel/文件夹    默认用户名密码为sentinel
# 启动命令：java -Dserver.port:8088 -jar sentinel-dashboard-1.8.2.jar
spring:
  application:
    name: sentinel-server
  cloud:
    sentinel:
      transport:
        # 通信的接口
        port: 8719
        # sentinel server地址
        dashboard: localhost:8080
      eager: true
server:
  port: 3000
eureka:
  client:
    instance:
      hostname: sentinel-server
    service-url:
      defaultZone: http://localhost:8000/eureka