package sudo.client_user.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table torg
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class org implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column torg.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   机构名称~~
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column torg.OrgName
     *
     * @mbg.generated
     */
    private String orgname;

    /**
     * Database Column Remarks:
     *   机构所属~~
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column torg.parentId
     *
     * @mbg.generated
     */
    private String parentid;

    /**
     * Database Column Remarks:
     *   机构数据ID~~
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column torg.OrgDataKey
     *
     * @mbg.generated
     */
    private String orgdatakey;

    /**
     * Database Column Remarks:
     *   机构类型~~
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column torg.OrgType
     *
     * @mbg.generated
     */
    private Integer orgtype;

    /**
     * Database Column Remarks:
     *   所属域~~
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column torg.DomainId
     *
     * @mbg.generated
     */
    private Integer domainid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table torg
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column torg.id
     *
     * @return the value of torg.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column torg.id
     *
     * @param id the value for torg.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column torg.OrgName
     *
     * @return the value of torg.OrgName
     *
     * @mbg.generated
     */
    public String getOrgname() {
        return orgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column torg.OrgName
     *
     * @param orgname the value for torg.OrgName
     *
     * @mbg.generated
     */
    public void setOrgname(String orgname) {
        this.orgname = orgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column torg.parentId
     *
     * @return the value of torg.parentId
     *
     * @mbg.generated
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column torg.parentId
     *
     * @param parentid the value for torg.parentId
     *
     * @mbg.generated
     */
    public void setParentid(String parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column torg.OrgDataKey
     *
     * @return the value of torg.OrgDataKey
     *
     * @mbg.generated
     */
    public String getOrgdatakey() {
        return orgdatakey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column torg.OrgDataKey
     *
     * @param orgdatakey the value for torg.OrgDataKey
     *
     * @mbg.generated
     */
    public void setOrgdatakey(String orgdatakey) {
        this.orgdatakey = orgdatakey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column torg.OrgType
     *
     * @return the value of torg.OrgType
     *
     * @mbg.generated
     */
    public Integer getOrgtype() {
        return orgtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column torg.OrgType
     *
     * @param orgtype the value for torg.OrgType
     *
     * @mbg.generated
     */
    public void setOrgtype(Integer orgtype) {
        this.orgtype = orgtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column torg.DomainId
     *
     * @return the value of torg.DomainId
     *
     * @mbg.generated
     */
    public Integer getDomainid() {
        return domainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column torg.DomainId
     *
     * @param domainid the value for torg.DomainId
     *
     * @mbg.generated
     */
    public void setDomainid(Integer domainid) {
        this.domainid = domainid;
    }
}