server:
  port: 9002
spring:
  application:
    name: client-chat
  #开启重试功能
  cloud.loadbalancer.retry.enabled: true
eureka:
  instance:
    hostname: client-chat
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
feign:
  hystrix:
    enabled: true
client-user:
  ribbon:
    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #配置规则 随机
    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule #配置规则 重试
    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
    #配置规则 最空闲连接策略
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule
    #连接超时时间
    ConnectTimeout: 250
    #数据读取超时时间
    ReadTimeout: 1000
    #是否对所有操作都进行操作
    OkToRetryOnAllOperations: true
    #切换实例的重试次数
    MaxAutoRetriesNextServer: 1
    #对当前实例的重试次数
    MaxAutoRetires: 1