server:
  port: 9002
spring:
  application:
    name: client-chat
  #开启重试功能
  cloud.loadbalancer.retry.enabled: true
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true  #开启请求压缩
      mime-types: text/html,application/xml,application/json #设置压缩类型
      min-request-size: 2048 #设置触发压缩的大小限制
    response:
      enabled: true #开启响应压缩
logging:
  config: classpath:logback.xml
  level:
    sudo.clientchat: debug   # 用于feign的日志的记录详细程度与FeignConfig配合使用