server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tianlaisha/sudo-cloud
          search-paths: config
          default-label: master
          force-pull: true
          username: tianlaisha
          password: glz123456```
eureka:
  instance:
    hostname: config-server
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka

