package sudo.client_user.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import sudo.client_user.entity.org;
import sudo.client_user.entity.orgExample;

@Repository
public interface orgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torg
     *
     * @mbg.generated
     */
    long countByExample(orgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torg
     *
     * @mbg.generated
     */
    int deleteByExample(orgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torg
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torg
     *
     * @mbg.generated
     */
    int insert(org record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torg
     *
     * @mbg.generated
     */
    int insertSelective(org record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torg
     *
     * @mbg.generated
     */
    List<org> selectByExample(orgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torg
     *
     * @mbg.generated
     */
    org selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torg
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") org record, @Param("example") orgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torg
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") org record, @Param("example") orgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torg
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(org record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torg
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(org record);
}